# ubuntu with python for programming stuff
FROM ubuntu:latest
LABEL maintainer="capybara NatZkh"

RUN apt-get update
RUN apt-get install -y python3 python3-dev python3-pip
RUN pip3 install jupyter

RUN mkdir /programming

WORKDIR "/programming"

EXPOSE 8888

#CMD ["jupyter notebook --allow-root --ip=*"]
